#define MAX_USER_RT_PRIO	(100)
#define MAX_RT_PRIO		MAX_USER_RT_PRIO
#define MAX_PRIO		(MAX_RT_PRIO + 40)
#define PF_KTHREAD	(0x00200000)

#define NR_OPEN_DEFAULT BITS_PER_LONG
#define _LINUX_CAPABILITY_U32S_3     (2)
#define _KERNEL_CAPABILITY_U32S    _LINUX_CAPABILITY_U32S_3
#define TASK_COMM_LEN (16)

#define KERNEL_OFFSET (0x080000)
